# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Master

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AssetPathRaw(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssetPathRaw()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssetPathRaw(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AssetPathRawBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x44\x34\x41\x4F", size_prefixed=size_prefixed)

    # AssetPathRaw
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AssetPathRaw
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from D4L.TakashoFes.Master.AssetPathRawEntry import AssetPathRawEntry
            obj = AssetPathRawEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AssetPathRaw
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AssetPathRaw
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def AssetPathRawStart(builder): builder.StartObject(1)
def Start(builder):
    return AssetPathRawStart(builder)
def AssetPathRawAddEntries(builder, entries): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)
def AddEntries(builder, entries):
    return AssetPathRawAddEntries(builder, entries)
def AssetPathRawStartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEntriesVector(builder, numElems):
    return AssetPathRawStartEntriesVector(builder, numElems)
def AssetPathRawEnd(builder): return builder.EndObject()
def End(builder):
    return AssetPathRawEnd(builder)